# This is the yaml configuration file for dnsproxy with minimal working
# configuration, all the options available can be seen with ./dnsproxy --help.
# To use it within dnsproxy specify the --config-path=/<path-to-config.yaml>
# option.  Any other command-line options specified will override the values
# from the config file.
---
bootstrap:
  - "9.9.9.9:53"
listen-addrs:
  - "0.0.0.0"
listen-ports:
  - 53
max-go-routines: 10
ratelimit: 0
udp-buf-size: 0
upstream:
  - "quic://p0.freedns.controld.com"
  - "quic://uncensored.dns.dnswarden.com"
  - "quic://dnsforge.de"
  - "tls://dns.quad9.net"
  - "tls://1dot1dot1dot1.cloudflare-dns.com"
  - "tls://security-filter-dns.cleanbrowsing.org"
  - "tls://dns.adguard.com"
timeout: '10s'
cache: true
cache-optimistic: true
blocked_domains_lists:
  - "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/tif.txt"
  - "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/ultimate.txt"
  - "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/dyndns.txt"
  - "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/hoster.txt"
  - "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/gambling.txt"
output: "/tmp/dnsproxy.log"
