# This is the yaml configuration file for dnsproxy with minimal working
# configuration, all the options available can be seen with ./dnsproxy --help.
# To use it within dnsproxy specify the --config-path=/<path-to-config.yaml>
# option.  Any other command-line options specified will override the values
# from the config file.
# https://avoidthehack.com/best-dns-privacy
# https://european-alternatives.eu/category/public-dns
# https://github.com/paulmillr/encrypted-dns
# https://github.com/pengelana/blocklist
# https://github.com/DNSCrypt/dnscrypt-resolvers/blob/master/v3/public-resolvers.md
# https://github.com/nickspaargaren/no-google/blob/master/google-domains
# https://www.dnscry.pt/public-resolvers/

# https://github.com/FiloSottile/mkcert
# https://deliciousbrains.com/ssl-certificate-authority-for-local-https-development/
# https://www.youtube.com/watch?v=SlcrTSvMioU
# https://www.positioniseverything.net/x509-certificate-signed-by-unknown-authority/
# https://stackoverflow.com/questions/64814173/how-do-i-use-sans-with-openssl-instead-of-common-name
# https://tutorialedge.net/golang/creating-simple-web-server-with-golang/
# https://stackoverflow.com/questions/10175812/how-to-generate-a-self-signed-ssl-certificate-using-openssl

# https://www.baeldung.com/linux/add-self-signed-certificate-trusted-list
# https://github.com/ChristianLempa/cheat-sheets/blob/main/misc/ssl-certs.md
---
bootstrap:
  - "9.9.9.9:53"
listen-addrs:
  - "0.0.0.0"
listen-ports:
  - 53
max-go-routines: 20
ratelimit: 0
http3: true
all-servers: false
udp-buf-size: 0
upstream:
  - "quic://p0.freedns.controld.com"
  - "quic://dnsforge.de"
  - "quic://unfiltered.adguard-dns.com"
  - "quic://zero.dns0.eu"
  - "tls://dns.quad9.net"
  - "tls://one.one.one.one"
  - "tls://dns.mullvad.net"
  - "tls://private.canadianshield.cira.ca"
  - "tls://dot1.applied-privacy.net"
  - "tls://kaitain.restena.lu"
  - "tls://dns3.digitalcourage.de"
  - "tls://dns.digitale-gesellschaft.ch"
  - "https://doh.dns.sb/dns-query"
  - "https://doh.tiar.app/dns-query"
  - "https://dns.artikel10.org/dns-query"
  - "https://doh.opendns.com/dns-query"
  - "https://sky.rethinkdns.com/1:AAkACAQA"
  - "https://dns.dnswarden.com/uncensored"
  - "https://doh.cleanbrowsing.org/doh/security-filter/"
  - "[/google.pl/]tls://dns.google"
  - "[/google.com/]tls://dns.google"
  - "[/googleusercontent.com/]tls://dns.google"
  - "[/gstatic.com/]tls://dns.google"
  - "[/youtube.com/]tls://dns.google"
  - "[/ytimg.com/]tls://dns.google"
  - "[/ggpht.com/]tls://dns.google"
  - "[/googleapis.com/]tls://dns.google"
  - "[/googlevideo.com/]tls://dns.google"
timeout: '10s'
cache: true
cache-optimistic: true
cache-size: 4194304
ipv6-disabled: true
blocked_domains_lists:
  - "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/tif.txt"
  - "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/ultimate.txt"
  - "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/dyndns.txt"
  - "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/hoster.txt"
  - "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/gambling.txt"
  - "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/doh-vpn-proxy-bypass.txt"
fallback:
    - "quic://x-hagezi-ultimate.freedns.controld.com"
    - "https://freedns.controld.com/no-ads-malware-typo"
domains_excluded_from_blocking:
    - "*.wordpress.com"
    - "*.blogspot.com"
    - "*.blogger.com"
    - "*.freedns.controld.com"
    - "*.vpn-api.proton.me"
    - "*.protonstatus.com"
    - "*.protonvpn.ch"
    - "*.protonvpn.com"
    - "*.protonvpn.net"
    - "*.ivpn.net"
    - "*.mullvad.net"
    - "*.cleanbrowsing.org"
    - "*.freeddns.org"
stats_port: 9999
https-port:
  - 443
tls-port:
  - 853
quic-port:
  - 853
tls-crt: "rfdns.freeddns.org.crt"
tls-key: "rfdns.freeddns.org.key"
insecure: true
output: "/tmp/dnsproxy.log"
