# This is the yaml configuration file for dnsproxy with minimal working
# configuration, all the options available can be seen with ./dnsproxy --help.
# To use it within dnsproxy specify the --config-path=/<path-to-config.yaml>
# option.  Any other command-line options specified will override the values
# from the config file.
# https://avoidthehack.com/best-dns-privacy
# https://european-alternatives.eu/category/public-dns
# https://github.com/paulmillr/encrypted-dns
# https://github.com/pengelana/blocklist
# https://github.com/DNSCrypt/dnscrypt-resolvers/blob/master/v3/public-resolvers.md
---
bootstrap:
  - "9.9.9.9:53"
listen-addrs:
  - "0.0.0.0"
listen-ports:
  - 53
max-go-routines: 20
ratelimit: 0
http3: true
all-servers: false
udp-buf-size: 0
upstream:
  - "quic://p0.freedns.controld.com"
  - "quic://dnsforge.de"
  - "quic://unfiltered.adguard-dns.com"
  - "quic://zero.dns0.eu"
  - "tls://dns.quad9.net"
  - "tls://one.one.one.one"
  - "tls://security-filter-dns.cleanbrowsing.org"
  - "tls://dns.mullvad.net"
  - "tls://private.canadianshield.cira.ca"
  - "tls://dot.sb"
  - "tls://dot1.applied-privacy.net"
  - "tls://kaitain.restena.lu"
  - "tls://dns3.digitalcourage.de"
  - "tls://dns.digitale-gesellschaft.ch"
  - "https://doh.tiar.app/dns-query"
  - "https://dns.artikel10.org/dns-query"
  - "https://doh.opendns.com/dns-query"
  - "[/google.pl/]tls://dns.google"
  - "[/google.com/]tls://dns.google"
  - "[/lh3.googleusercontent.com/]tls://dns.google"
  - "[/gstatic.com/]tls://dns.google"
  - "[/youtube.com/]tls://dns.google"
  - "[/i.ytimg.com/]tls://dns.google"
  - "[/yt3.ggpht.com/]tls://dns.google"
  - "[/googleapis.com/]tls://dns.google"
  - "[/googlevideo.com/]tls://dns.google"
timeout: '10s'
cache: true
cache-optimistic: true
cache-size: 4194304
blocked_domains_lists:
  - "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/tif.txt"
  - "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/ultimate.txt"
  - "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/dyndns.txt"
  - "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/hoster.txt"
  - "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/gambling.txt"
fallback:
    - "quic://x-hagezi-ultimate.freedns.controld.com"
output: "/tmp/dnsproxy.log"
