# This is the yaml configuration file for dnsproxy with minimal working
# configuration, all the options available can be seen with ./dnsproxy --help.
# To use it within dnsproxy specify the --config-path=/<path-to-config.yaml>
# option.  Any other command-line options specified will override the values
# from the config file.
# https://avoidthehack.com/best-dns-privacy
# https://european-alternatives.eu/category/public-dns
# https://github.com/paulmillr/encrypted-dns
# https://github.com/pengelana/blocklist
# https://github.com/DNSCrypt/dnscrypt-resolvers/blob/master/v3/public-resolvers.md
# https://github.com/nickspaargaren/no-google/blob/master/google-domains
# https://www.dnscry.pt/public-resolvers/
# https://adguard-dns.io/kb/general/dns-providers/
# https://www.reddit.com/r/degoogle/comments/129n87v/is_there_any_secured_dns_address_available_for/

# https://github.com/FiloSottile/mkcert
# https://deliciousbrains.com/ssl-certificate-authority-for-local-https-development/
# https://www.youtube.com/watch?v=SlcrTSvMioU
# https://www.positioniseverything.net/x509-certificate-signed-by-unknown-authority/
# https://stackoverflow.com/questions/64814173/how-do-i-use-sans-with-openssl-instead-of-common-name
# https://tutorialedge.net/golang/creating-simple-web-server-with-golang/
# https://stackoverflow.com/questions/10175812/how-to-generate-a-self-signed-ssl-certificate-using-openssl

# https://www.baeldung.com/linux/add-self-signed-certificate-trusted-list
# https://github.com/ChristianLempa/cheat-sheets/blob/main/misc/ssl-certs.md
# https://www.ipfire.org/docs/dns/public-servers
---
bootstrap:
  - "9.9.9.9:53"
  - "149.112.112.112:53"
  - "1.1.1.1:53"
  - "76.76.2.0:53"
listen-addrs:
  - "0.0.0.0"
listen-ports:
  - 53000
max-go-routines: 20
ratelimit: 0
http3: true
all-servers: false
udp-buf-size: 0
upstream:
  - "tls://private.canadianshield.cira.ca"
  - "tls://dot1.applied-privacy.net"
  - "tls://resolv.flokinet.net"
  - "tls://dns3.digitalcourage.de"
  - "tls://dns.digitale-gesellschaft.ch"
  - "tls://dns.cmrg.net"
  - "tls://recursor01.dns.lightningwirelabs.com"
  - "tls://dot.linuxpatch.com"
  - "tls://dns-ga.com"
  - "https://freedns.controld.com/p0"
  - "https://dnsforge.de/dns-query"
  - "https://unfiltered.adguard-dns.com/dns-query"
  - "https://dns0.eu/"
  - "https://dnspub.restena.lu/dns-query"  
  - "https://doh.ffmuc.net/dns-query"
  - "https://anycast.uncensoreddns.org/dns-query"
  - "https://dns.mullvad.net/dns-query"
  - "https://dns.quad9.net/dns-query"
  - "https://one.one.one.one/dns-query"
  - "https://doh.dns.sb/dns-query"
  - "https://doh.tiar.app/dns-query"
  - "https://dns.artikel10.org/dns-query"
  - "https://doh.opendns.com/dns-query"
  - "https://sky.rethinkdns.com/1:AAkACAQA"
  - "https://secure.avastdns.com/dns-query"
  - "[/google.pl/]https://dns.google/dns-query"
  - "[/google.com/]https://dns.google/dns-query"
  - "[/googleusercontent.com/]https://dns.google/dns-query"
  - "[/gstatic.com/]https://dns.google/dns-query"
  - "[/youtube.com/]https://dns.google/dns-query"
  - "[/ytimg.com/]https://dns.google/dns-query"
  - "[/ggpht.com/]https://dns.google/dns-query"
  - "[/googleapis.com/]https://dns.google/dns-query"
  - "[/googlevideo.com/]https://dns.google/dns-query"
timeout: '10s'
cache: true
cache-optimistic: true
cache-size: 4194304
ipv6-disabled: false
blocked_domains_lists:
  - "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/tif.txt"
  - "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/ultimate.txt"
  - "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/dyndns.txt"
  - "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/hoster.txt"
  - "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/gambling.txt"
  - "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/doh-vpn-proxy-bypass.txt"
fallback:
    - "https://dns.quad9.net/dns-query"
    - "https://one.one.one.one/dns-query"
domains_excluded_from_blocking:
    - "*.wordpress.com"
    - "*.blogspot.com"
    - "*.blogger.com"
    - "*.freedns.controld.com"
    - "*.vpn-api.proton.me"
    - "*.protonstatus.com"
    - "*.protonvpn.ch"
    - "*.protonvpn.com"
    - "*.protonvpn.net"
    - "*.ivpn.net"
    - "*.mullvad.net"
    - "*.cleanbrowsing.org"
    - "*.freeddns.org"
    - "*.dns.google"
    - "*.imx.to"
    - "*.dnswarden.com"
    - "*.dns.quad9.net"
    - "*.one.one.one.one"
domains_excluded_from_caching:
    - "*.freeddns.org"
stats_port: 9999
#tls-port:
#  - 853
#quic-port:
#  - 853
#tls-crt: "rfdns.freeddns.org.crt"
#tls-key: "rfdns.freeddns.org.key"
insecure: true
output: "dnsproxy.log"
